"""initial_schema

Revision ID: 981adc9f71c7
Revises: 
Create Date: 2026-07-20 17:11:21.219929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '981adc9f71c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.Text(), nullable=True),
    sa.Column('candidate_email', sa.Text(), nullable=True),
    sa.Column('candidate_phone', sa.Text(), nullable=True),
    sa.Column('current_designation', sa.Text(), nullable=True),
    sa.Column('current_company', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('current_location', sa.Text(), nullable=True),
    sa.Column('preferred_location', sa.Text(), nullable=True),
    sa.Column('notice_period', sa.Text(), nullable=True),
    sa.Column('current_ctc', sa.Text(), nullable=True),
    sa.Column('expected_ctc', sa.Text(), nullable=True),
    sa.Column('highest_qualification', sa.Text(), nullable=True),
    sa.Column('university', sa.Text(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('duplicate_status', sa.Text(), nullable=True),
    sa.Column('canonical_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_candidate_email'), 'candidates', ['candidate_email'], unique=True)
    op.create_index(op.f('ix_candidates_candidate_phone'), 'candidates', ['candidate_phone'], unique=False)
    op.create_index('ix_candidates_skills', 'candidates', ['skills'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidates_tags', 'candidates', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('successful_rows', sa.Integer(), nullable=True),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duplicate_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id_a', sa.UUID(), nullable=False),
    sa.Column('candidate_id_b', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id_a'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['candidate_id_b'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id_a', 'candidate_id_b', name='uq_duplicate_pair')
    )
    op.create_index('ix_duplicate_flags_status', 'duplicate_flags', ['status'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('stored_filename', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_table('parse_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('parser_used', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parse_jobs_resume_id', 'parse_jobs', ['resume_id'], unique=False)
    op.create_index('ix_parse_jobs_status', 'parse_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parse_jobs_status', table_name='parse_jobs')
    op.drop_index('ix_parse_jobs_resume_id', table_name='parse_jobs')
    op.drop_table('parse_jobs')
    op.drop_table('resumes')
    op.drop_index('ix_duplicate_flags_status', table_name='duplicate_flags')
    op.drop_table('duplicate_flags')
    op.drop_table('import_batches')
    op.drop_index('ix_candidates_tags', table_name='candidates', postgresql_using='gin')
    op.drop_index('ix_candidates_skills', table_name='candidates', postgresql_using='gin')
    op.drop_index(op.f('ix_candidates_candidate_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
